import { act,cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { createHistoricalReactivationApi } from '../src/api/historical-reactivation-api.js';
import { HistoricalReactivationReview } from '../src/components/app/HistoricalReactivationReview.jsx';
import { batchId,capability,makeAuth,makeReview,makeReceipt,makeInspection,intentId } from './historical-fixtures.js';
let auth,client;
vi.mock('../src/auth/auth-context.js',()=>({useAuth:()=>auth}));
beforeEach(()=>{auth=makeAuth();client={preview:vi.fn().mockResolvedValue({data:makeReview()}),confirm:vi.fn().mockResolvedValue({data:makeReceipt()}),status:vi.fn().mockResolvedValue({data:makeReceipt()}),inspect:vi.fn().mockResolvedValue({data:makeInspection()}),reconcile:vi.fn().mockResolvedValue({data:makeReceipt('awaiting_native').items[0]})};});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.useRealTimers();});
const mount=(props={})=>render(<HistoricalReactivationReview open config={capability} apiClient={client} createRequestId={()=>batchId} onClose={vi.fn()} {...props}/>);
async function preview(){fireEvent.change(screen.getByLabelText('Точні артикули, по одному в рядку'),{target:{value:'AR-000001\nSV-000002\nMISSING'}});fireEvent.click(screen.getByRole('button',{name:'Перевірити товари'}));await screen.findByText('Можна відновити: 2. Потребують уваги: 0. Пропущено: 1.');}
async function selectAndConfirm(){fireEvent.click(screen.getByRole('checkbox',{name:'Обрати AR-000001'}));fireEvent.click(screen.getByRole('checkbox',{name:/Погоджую/}));fireEvent.click(screen.getByRole('button',{name:'Відновити вибране (1)'}));}
it('opening is inert and ordinary restore remains explicitly separate; exact subset requires explicit acknowledgement',async()=>{
 mount();expect(client.preview).not.toHaveBeenCalled();expect(client.confirm).not.toHaveBeenCalled();await preview();
 expect(screen.getByRole('checkbox',{name:'Обрати AR-000001'}).checked).toBe(false);expect(screen.getByRole('checkbox',{name:'Обрати MISSING'}).disabled).toBe(true);
 expect(screen.getByRole('button',{name:'Відновити вибране (0)'}).disabled).toBe(true);expect(screen.getByText(/Не знайдено у Manager: 1/)).toBeTruthy();
 await selectAndConfirm();await screen.findByText('Результати відновлення');expect(client.confirm).toHaveBeenCalledTimes(1);
 const cmd=client.confirm.mock.calls[0][0];expect(cmd.skus).toEqual(['AR-000001','SV-000002','MISSING']);expect(cmd.selectedSkus).toEqual(['AR-000001']);expect(cmd.idempotencyKey).toBe(batchId);expect(cmd.confirmCurrentFactsAndHiddenUpdate).toBe(true);
 expect(screen.getByText('Це ще не підтвердження завершення всіх етапів доставки. Товар не вмикається для показу.')).toBeTruthy();
});
it.each(['manager','missing-permission','missing-capability'])('cannot request protected flow without real authority: %s',async(mode)=>{
 if(mode==='manager')auth.roles=[{key:'manager'}];if(mode==='missing-permission')auth.permissions=auth.permissions.filter(p=>p!=='history.view');
 mount({config:mode==='missing-capability'?{}:capability});expect(screen.queryByRole('textbox')).toBeNull();expect(client.preview).not.toHaveBeenCalled();expect(client.status).not.toHaveBeenCalled();
});
it('missing atomic update-only adapter blocks selection and never offers fake create fallback',async()=>{
 const r=makeReview();r.items=r.items.map(item=>item.disposition==='eligible'?{...item,disposition:'blocked',reasonCode:'HISTORICAL_UPDATE_ONLY_ADAPTER_REQUIRED',prerequisites:[{code:'ATOMIC_UPDATE_ONLY_SUPPORTED',met:false}],blockerCodes:['HISTORICAL_UPDATE_ONLY_ADAPTER_REQUIRED']}:item);r.counts={eligible:0,blocked:2,skipped:1};client.preview.mockResolvedValueOnce({data:r});mount();
 fireEvent.change(screen.getByLabelText('Точні артикули, по одному в рядку'),{target:{value:'AR-000001\nSV-000002\nMISSING'}});fireEvent.click(screen.getByRole('button',{name:'Перевірити товари'}));await screen.findByText(/Спочатку усуньте причини, зазначені у списку/);
 expect(screen.getAllByText(/Потрібен перевірений адаптер атомарного UPDATE/)).toHaveLength(2);expect(screen.getByRole('checkbox',{name:'Обрати AR-000001'}).disabled).toBe(true);expect(client.confirm).not.toHaveBeenCalled();
});
it('lost confirm keeps immutable UUID and exact membership; GET404 never permits resend or edits',async()=>{
 client.confirm.mockRejectedValueOnce(new Error('lost fixture'));client.status.mockRejectedValueOnce({response:{status:404}});mount();await preview();await selectAndConfirm();await screen.findByText(/Результат ще не підтверджено. Список/);
 expect(screen.getByLabelText('Точні артикули, по одному в рядку').disabled).toBe(true);expect(screen.getByRole('button',{name:'Закрити історичне рішення'}).disabled).toBe(true);
 fireEvent.click(screen.getByRole('button',{name:'Перевірити стан цього самого рішення'}));await screen.findByText(/Операцію за цим номером ще не знайдено/);expect(client.status).toHaveBeenCalledWith(batchId,{});expect(client.confirm).toHaveBeenCalledTimes(1);
 fireEvent.click(screen.getByRole('button',{name:'Перевірити стан цього самого рішення'}));await screen.findByText('Результати відновлення');expect(client.confirm).toHaveBeenCalledTimes(1);
});
it('stale proof is a definitive nonacceptance; requires a new explicit preview rather than automatic resend',async()=>{
 client.confirm.mockRejectedValueOnce({response:{status:409,data:{code:'HISTORICAL_REVIEW_STALE',error:'Перевірка застаріла на сервері'}}});mount();await preview();await selectAndConfirm();await screen.findByText('Перевірка застаріла на сервері');expect(screen.queryByText('Незмінний номер операції:')).toBeNull();expect(client.preview).toHaveBeenCalledTimes(1);expect(client.confirm).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Перевірити товари'})).toBeTruthy();
});
it('a malformed accepted membership stays uncertain and can recover solely by GET',async()=>{
 const r=makeReceipt();r.items[0].article='SV-000002';client.confirm.mockResolvedValueOnce({data:r});mount();await preview();await selectAndConfirm();await screen.findByText(/Результат ще не підтверджено. Список/);expect(screen.queryByText('Результати відновлення')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Перевірити стан цього самого рішення'}));await screen.findByText('Результати відновлення');expect(client.confirm).toHaveBeenCalledTimes(1);
});
it('fresh exact inspection plus explicit acknowledgement performs only local reconciliation and preserves native pending stage',async()=>{
 const onReceipt=vi.fn();mount({onReceipt});await preview();await selectAndConfirm();await screen.findByText('Результати відновлення');fireEvent.click(screen.getByRole('button',{name:'Перевірити прихований результат для AR-000001'}));await screen.findByText('Спостережений стан: 2 — прихований.');
 const button=screen.getByRole('button',{name:'Перевірити результат і завершити локальне рішення'});expect(button.disabled).toBe(true);expect(client.reconcile).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('checkbox',{name:/Підтверджую завершення лише локального рішення/}));fireEvent.click(button);
 await screen.findByText(/Приховування перевірено; підтвердження UPDATE ще очікується/);expect(client.reconcile).toHaveBeenCalledExactlyOnceWith(intentId,'d'.repeat(64));expect(onReceipt).toHaveBeenCalledTimes(1);expect(screen.getByText(/Це ще не підтвердження завершення всіх етапів/)).toBeTruthy();expect(screen.queryByText(/Приховування, локальне рішення та UPDATE підтверджено/)).toBeNull();
});
it('mismatched remote identity cannot expose local-completion acknowledgement',async()=>{
 client.inspect.mockResolvedValueOnce({data:{...makeInspection(),observedMagentoId:52}});mount();await preview();await selectAndConfirm();await screen.findByText('Результати відновлення');fireEvent.click(screen.getByRole('button',{name:'Перевірити прихований результат для AR-000001'}));await screen.findByText(/Сервер повернув неповну перевірку/);expect(screen.queryByRole('button',{name:'Перевірити результат і завершити локальне рішення'})).toBeNull();expect(client.reconcile).not.toHaveBeenCalled();
});
it('permission revoked during uncertain confirmation reveals no receipt; regrant permits GET recovery only',async()=>{
 let resolve;client.confirm.mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));const view=mount();await preview();await selectAndConfirm();await waitFor(()=>expect(client.confirm).toHaveBeenCalledTimes(1));auth={...auth,permissions:[]};view.rerender(<HistoricalReactivationReview open config={capability} apiClient={client} createRequestId={()=>batchId}/>);await act(async()=>resolve({data:makeReceipt()}));expect(screen.queryByText('Результати відновлення')).toBeNull();auth={...auth,permissions:makeAuth().permissions};view.rerender(<HistoricalReactivationReview open config={capability} apiClient={client} createRequestId={()=>batchId}/>);await screen.findByText(/Результат ще не підтверджено. Список/);fireEvent.click(screen.getByRole('button',{name:'Перевірити стан цього самого рішення'}));await screen.findByText('Результати відновлення');expect(client.confirm).toHaveBeenCalledTimes(1);
});
it('lost local reconciliation never resends or pretends native acknowledgement; status read exposes actual stage',async()=>{
 client.reconcile.mockRejectedValueOnce(new Error('lost local reply'));client.status.mockResolvedValueOnce({data:makeReceipt('awaiting_native')});mount();await preview();await selectAndConfirm();await screen.findByText('Результати відновлення');fireEvent.click(screen.getByRole('button',{name:'Перевірити прихований результат для AR-000001'}));await screen.findByText('Спостережений стан: 2 — прихований.');fireEvent.click(screen.getByRole('checkbox',{name:/Підтверджую завершення лише локального рішення/}));fireEvent.click(screen.getByRole('button',{name:'Перевірити результат і завершити локальне рішення'}));await screen.findByText(/Результат ще не підтверджено. Список/);fireEvent.click(screen.getByRole('button',{name:'Перевірити стан цього самого рішення'}));await screen.findByText(/Приховування перевірено; підтвердження UPDATE ще очікується/);expect(client.reconcile).toHaveBeenCalledTimes(1);expect(client.confirm).toHaveBeenCalledTimes(1);
});
it('review expiry disables confirmation and requires fresh review',async()=>{
 const r=makeReview();r.reviewExpiresAt=new Date(Date.now()-1000).toISOString();client.preview.mockResolvedValueOnce({data:r});mount();await preview();expect(screen.getByRole('checkbox',{name:'Обрати AR-000001'}).disabled).toBe(true);expect(screen.getByRole('checkbox',{name:/Погоджую/}).disabled).toBe(true);expect(screen.getByRole('button',{name:'Відновити вибране (0)'}).disabled).toBe(true);expect(client.confirm).not.toHaveBeenCalled();
});

it('synthetic 70-item review keeps 22 absent products out and submits only the one explicitly selected existing counterpart',async()=>{
 const r=makeReview();r.skus=Array.from({length:70},(_,i)=>i<48?'AR-'+String(i+1).padStart(6,'0'):'MISSING-'+i);r.items=r.skus.map((sku,i)=>i<48?{...r.items[0],inputSku:sku,article:sku,productId:i+1,remoteProductId:i+51}:{...r.items[2],inputSku:sku});r.counts={eligible:48,blocked:0,skipped:22};client.preview.mockResolvedValueOnce({data:r});mount();fireEvent.change(screen.getByLabelText('Точні артикули, по одному в рядку'),{target:{value:r.skus.join('\n')}});fireEvent.click(screen.getByRole('button',{name:'Перевірити товари'}));await screen.findByText('Можна відновити: 48. Потребують уваги: 0. Пропущено: 22.');expect(screen.getByText(/Не знайдено у Manager: 22/)).toBeTruthy();expect(screen.getAllByRole('checkbox',{name:/Обрати MISSING/}).every(input=>input.disabled)).toBe(true);await selectAndConfirm();await screen.findByText('Результати відновлення');expect(client.confirm.mock.calls[0][0].skus).toEqual(r.skus);expect(client.confirm.mock.calls[0][0].selectedSkus).toEqual(['AR-000001']);
});
it('explicit inspection refresh discards prior confirmation after a failed fresh read',async()=>{
 mount();await preview();await selectAndConfirm();await screen.findByText('Результати відновлення');fireEvent.click(screen.getByRole('button',{name:'Перевірити прихований результат для AR-000001'}));await screen.findByText('Спостережений стан: 2 — прихований.');fireEvent.click(screen.getByRole('checkbox',{name:/Підтверджую завершення лише локального рішення/}));client.inspect.mockRejectedValueOnce(new Error('fresh observation unavailable'));fireEvent.click(screen.getByRole('button',{name:'Перевірити прихований результат для AR-000001'}));await screen.findByText('fresh observation unavailable');expect(screen.queryByRole('button',{name:'Перевірити результат і завершити локальне рішення'})).toBeNull();expect(client.reconcile).not.toHaveBeenCalled();
});
it('pending receipt polls status without overlapping GETs or repeating confirmation, and completion displays three historical receipts',async()=>{
 const view=mount();await preview();await selectAndConfirm();await screen.findByText('Результати відновлення');vi.useFakeTimers();view.rerender(<HistoricalReactivationReview open={false} config={capability} apiClient={client} createRequestId={()=>batchId}/>);view.rerender(<HistoricalReactivationReview open config={capability} apiClient={client} createRequestId={()=>batchId}/>);let resolve;client.status.mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));await act(async()=>{await vi.advanceTimersByTimeAsync(5000);});expect(client.status).toHaveBeenCalledTimes(1);await act(async()=>{await vi.advanceTimersByTimeAsync(15000);});expect(client.status).toHaveBeenCalledTimes(1);expect(client.confirm).toHaveBeenCalledTimes(1);await act(async()=>resolve({data:makeReceipt('completed')}));expect(screen.getByText(/Приховування, локальне рішення та UPDATE підтверджено/)).toBeTruthy();await act(async()=>{await vi.advanceTimersByTimeAsync(15000);});expect(client.status).toHaveBeenCalledTimes(1);expect(client.confirm).toHaveBeenCalledTimes(1);
});

it('API transport uses GET-only status and inspection, with exactly one explicit local reconcile command and no resend',async()=>{
 const transport={post:vi.fn().mockResolvedValue({data:{}}),get:vi.fn().mockResolvedValue({data:{}})},api=createHistoricalReactivationApi(transport);await api.preview(['AR-000001']);const command={idempotencyKey:batchId};await api.confirm(command);await api.status(batchId);await api.inspect(intentId);await api.reconcile(intentId,'d'.repeat(64));expect(transport.get.mock.calls).toEqual([['/products/historical-reactivation/batches/'+batchId,{}],['/products/historical-reactivation/intents/'+intentId+'/inspection',{}]]);expect(transport.post.mock.calls).toEqual([['/products/historical-reactivation/preview',{skus:['AR-000001']}],['/products/historical-reactivation/confirm',command],['/products/historical-reactivation/reconcile',{intentId,reviewHash:'d'.repeat(64),confirmObservedHiddenResult:true}]]);
});
