import { act,cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { createMemoryRouter,RouterProvider } from 'react-router-dom';
import IntegrationTaskQueue from '../src/components/attention/IntegrationTaskQueue.jsx';
import SyncProblemsPage from '../src/pages/SyncProblemsPage.jsx';
let auth,client;
vi.mock('../src/auth/auth-context.js',()=>({useAuth:()=>auth}));
const transport=vi.hoisted(()=>({get:vi.fn(),post:vi.fn()}));
vi.mock('../src/lib/api.js',()=>({api:transport}));
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',otherId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const makeTask=(changes={})=>({id,revision:'1',state:'open',categoryCode:'AR',categoryLabel:'Каблучки',questionKey:'size',questionLabel:'Розмір',valueId:'29',valueLabel:'29 мм',reasonCode:'SOURCE_SUPPORT_DEFERRED_VALUE',message:'Потрібно перевірити обране значення та відповідність.',createdAt:'2026-10-05T09:00:00Z',createdBy:{id:1,displayName:'Менеджер'},repairHref:'/admin/magento/prepare?'+new URLSearchParams({category:'AR',question:'size',value:'29',returnTo:'/attention?integrationTask='+id}),resumeHref:'/products/create?integrationTask='+id,creationContext:{photoCount:2},productCreationAllowedLocally:true,deliveryAccepted:false,...changes});
const check=(changes={})=>({taskId:id,revision:'1',resolved:true,readiness:{status:'no_native_upgrade_blocker'},resolutionToken:'c'.repeat(64),...changes});
beforeEach(()=>{
 auth={roles:[{key:'administrator'}],permissions:['products.view','products.create','export_templates.manage'],principalLifetime:{id:'queue-owner',valid:true}};
 client={get:vi.fn().mockImplementation(async(url)=>({data:url==='/integration-tasks'?{items:[makeTask()],nextOffset:null}:url.endsWith('/resolution')?check():makeTask()})),post:vi.fn().mockResolvedValue({data:makeTask({state:'resolved',revision:'2'})})};transport.get.mockReset();transport.post.mockReset();
});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
const mount=(props={})=>render(<IntegrationTaskQueue apiClient={client} selectedTaskId={id} {...props}/>);
it('exact deep-link reads the selected task and no resolution or mutation occurs until explicit interaction',async()=>{
 mount();await screen.findByRole('article',{name:'Вибрана задача інтеграції'});await screen.findByRole('link',{name:'Відкрити точне налаштування'});expect(client.get.mock.calls.map(([url])=>url)).toEqual(['/integration-tasks','/integration-tasks/'+id]);expect(client.post).not.toHaveBeenCalled();expect(screen.getByRole('link',{name:'Відкрити точне налаштування'}).getAttribute('href')).toBe(makeTask().repairHref);expect(screen.getByRole('link',{name:'Повернутися до створення товару'}).getAttribute('href')).toBe('/products/create?integrationTask='+id);expect(screen.getByText('Фото зі спроби створення: 2.')).toBeTruthy();
});
it('creator can read own task and resume but has no administrator repair or resolve action',async()=>{
 auth.roles=[{key:'manager'}];auth.permissions=['products.create'];mount();await screen.findByRole('link',{name:'Повернутися до створення товару'});expect(screen.queryByRole('link',{name:'Відкрити точне налаштування'})).toBeNull();expect(screen.queryByRole('button',{name:'Перевірити результат налаштування'})).toBeNull();expect(client.post).not.toHaveBeenCalled();
});
it('custom role with management permissions cannot resolve and unauthorized readers trigger no task API',async()=>{
 auth.roles=[{key:'manager'}];mount();await screen.findByRole('link',{name:'Повернутися до створення товару'});expect(screen.queryByRole('button',{name:'Перевірити результат налаштування'})).toBeNull();cleanup();client.get.mockClear();auth.permissions=['products.view'];mount();expect(screen.getByText(/Перегляд цієї задачі інтеграції недоступний/)).toBeTruthy();expect(client.get).not.toHaveBeenCalled();
});
it('explicit fresh check plus acknowledged local completion uses exactly task revision/token and never claims Magento delivery',async()=>{
 mount();await screen.findByRole('button',{name:'Перевірити результат налаштування'});fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await screen.findByText('Поточна перевірка дозволяє підтвердити вирішення цієї задачі.');const confirm=screen.getByRole('button',{name:'Позначити задачу вирішеною'});expect(confirm.disabled).toBe(true);expect(client.post).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('checkbox',{name:/Підтверджую лише вирішення/}));fireEvent.click(confirm);await screen.findByText('Задачу вирішено');expect(client.post).toHaveBeenCalledExactlyOnceWith('/integration-tasks/'+id+'/resolve',{expectedRevision:'1',resolutionToken:'c'.repeat(64)});expect(screen.getByText(/доставки в Magento це не підтверджує/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Оновити задачі'}));await waitFor(()=>expect(client.get.mock.calls.filter(([url])=>url==='/integration-tasks/'+id)).toHaveLength(3));expect(screen.getByText('Задачу вирішено')).toBeTruthy();expect(screen.queryByRole('button',{name:'Перевірити результат налаштування'})).toBeNull();expect(client.post).toHaveBeenCalledTimes(1);
});
it('not-ready and missing-token checks cannot offer a local completion button',async()=>{
 client.get.mockImplementation(async(url)=>({data:url==='/integration-tasks'?{items:[],nextOffset:null}:url.endsWith('/resolution')?check({resolved:false,resolutionToken:null}):makeTask()}));mount();await screen.findByRole('button',{name:'Перевірити результат налаштування'});fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await screen.findByText('Поточні налаштування ще не усунули причину задачі.');expect(screen.queryByRole('button',{name:'Позначити задачу вирішеною'})).toBeNull();expect(client.post).not.toHaveBeenCalled();client.get.mockImplementation(async(url)=>({data:url==='/integration-tasks'?{items:[],nextOffset:null}:url.endsWith('/resolution')?check({resolutionToken:null}):makeTask()}));fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await screen.findByText(/Перевірка не повернула підтвердження/);expect(screen.queryByRole('button',{name:'Позначити задачу вирішеною'})).toBeNull();
});
it('lost resolve response allows only same-task GET recovery; an open or missing read cannot authorize resend',async()=>{
 client.post.mockRejectedValueOnce(new Error('lost response'));mount();await screen.findByRole('button',{name:'Перевірити результат налаштування'});fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await screen.findByRole('checkbox');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Позначити задачу вирішеною'}));await screen.findByText(/Результат вирішення ще не підтверджено/);expect(screen.getByRole('button',{name:'Перевірити результат налаштування'}).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Оновити задачі'}));await waitFor(()=>expect(client.get.mock.calls.filter(([url])=>url==='/integration-tasks/'+id)).toHaveLength(2));expect(client.post).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Перевірити результат налаштування'}).disabled).toBe(true);client.get.mockImplementation(async(url)=>{if(url==='/integration-tasks/'+id)throw{response:{status:404}};return{data:{items:[],nextOffset:null}};});fireEvent.click(screen.getByRole('button',{name:'Оновити задачі'}));await screen.findByText(/Задачу не знайдено. Це не підтверджує результат/);expect(client.post).toHaveBeenCalledTimes(1);client.get.mockImplementation(async(url)=>({data:url==='/integration-tasks'?{items:[],nextOffset:null}:makeTask({state:'resolved',revision:'2'})}));fireEvent.click(screen.getByRole('button',{name:'Оновити задачі'}));await screen.findByText('Задачу вирішено');expect(client.post).toHaveBeenCalledTimes(1);
});
it('definitive stale resolution rejects proof and requires a new explicit check without auto POST',async()=>{
 client.post.mockRejectedValueOnce({response:{status:409,data:{code:'INTEGRATION_TASK_RESOLUTION_STALE',error:'Попередню перевірку не прийнято'}}});mount();await screen.findByRole('button',{name:'Перевірити результат налаштування'});fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await screen.findByRole('checkbox');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Позначити задачу вирішеною'}));await screen.findByText('Попередню перевірку не прийнято');expect(screen.queryByRole('button',{name:'Позначити задачу вирішеною'})).toBeNull();expect(client.post).toHaveBeenCalledTimes(1);await waitFor(()=>expect(screen.getByRole('button',{name:'Перевірити результат налаштування'}).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await screen.findByRole('checkbox');expect(client.post).toHaveBeenCalledTimes(1);
});
it('permission scope change drops late administrator all-task results and reads only the creator scope',async()=>{
 let resolve;client.get.mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));const view=mount({selectedTaskId:null});auth={...auth,roles:[{key:'manager'}],permissions:['products.create']};client.get.mockResolvedValueOnce({data:{items:[],nextOffset:null}});view.rerender(<IntegrationTaskQueue apiClient={client} selectedTaskId={null}/>);await screen.findByText('Відкритих задач інтеграції немає.');await act(async()=>resolve({data:{items:[makeTask()],nextOffset:null}}));expect(screen.queryByText('Каблучки · Розмір · 29 мм')).toBeNull();expect(client.post).not.toHaveBeenCalled();
});
it('late selected-task response cannot replace a newer exact task',async()=>{
 let resolve;client.get.mockImplementation(async(url)=>url==='/integration-tasks/'+id?new Promise(done=>{resolve=done;}):{data:url==='/integration-tasks'?{items:[],nextOffset:null}:makeTask({id:otherId,categoryLabel:'Інша категорія',repairHref:null,resumeHref:null})});const view=mount();await waitFor(()=>expect(resolve).toBeTypeOf('function'));view.rerender(<IntegrationTaskQueue apiClient={client} selectedTaskId={otherId}/>);await screen.findByRole('heading',{name:'Новий незбережений товар · Інша категорія · Розмір · 29 мм'});await act(async()=>resolve({data:makeTask()}));expect(screen.queryByRole('heading',{name:'Новий незбережений товар · Каблучки · Розмір · 29 мм'})).toBeNull();
});
it.each([404,'malformed'])('unavailable or malformed queue cannot masquerade as an empty successful queue: %s',async(kind)=>{
 client.get.mockImplementation(async()=>{if(kind===404)throw{response:{status:404}};return{data:{categories:{AR:{}}}};});mount({selectedTaskId:null});await screen.findByText(kind===404?/Задачі інтеграції ще недоступні/:/Не вдалося прочитати задачі інтеграції/);expect(screen.queryByText('Відкритих задач інтеграції немає.')).toBeNull();
});
it('unsafe or wrong-context repair and resume links are omitted instead of opening generic settings or external pages',async()=>{
 client.get.mockResolvedValue({data:makeTask({repairHref:'https://external.invalid/settings',resumeHref:'/products/create?integrationTask='+otherId})});mount();await screen.findByText(/Посилання на точне налаштування не підтверджено/);expect(screen.queryByRole('link')).toBeNull();expect(client.post).not.toHaveBeenCalled();
});
it('Attention integrationTask deep-link selects exact task and preserves the existing delivery queue without any auto POST',async()=>{
 transport.get.mockImplementation(async(url)=>({data:url==='/integration-tasks'?{items:[makeTask()],nextOffset:null}:url==='/integration-tasks/'+id?makeTask():url==='/magento/problems/page'?{items:[],pageInfo:{total:0,hasNext:false,hasPrevious:false}}:{}}));const router=createMemoryRouter([{path:'*',element:<SyncProblemsPage/>}],{initialEntries:['/attention?integrationTask='+id]});render(<RouterProvider router={router}/>);const article=await screen.findByRole('article',{name:'Вибрана задача інтеграції'});await within(article).findByRole('heading',{name:'Новий незбережений товар · Каблучки · Розмір · 29 мм'});expect(transport.get.mock.calls.map(([url])=>url).filter(url=>url.startsWith('/integration-tasks'))).toEqual(['/integration-tasks','/integration-tasks/'+id]);expect(transport.post).not.toHaveBeenCalled();expect(screen.getByRole('heading',{name:'Проблеми доставки товарів'})).toBeTruthy();
});

it('changing selection during an explicit check releases only the finished old operation without adopting old proof',async()=>{
 let complete;client.get.mockImplementation(async(url)=>{if(url==='/integration-tasks/'+id+'/resolution')return new Promise(done=>{complete=done;});return{data:url==='/integration-tasks'?{items:[],nextOffset:null}:makeTask({id:url.endsWith(otherId)?otherId:id,repairHref:null,resumeHref:null})};});
 const view=mount();await screen.findByRole('button',{name:'Перевірити результат налаштування'});fireEvent.click(screen.getByRole('button',{name:'Перевірити результат налаштування'}));await waitFor(()=>expect(complete).toBeTypeOf('function'));
 view.rerender(<IntegrationTaskQueue apiClient={client} selectedTaskId={otherId}/>);await waitFor(()=>expect(client.get.mock.calls.some(([url])=>url==='/integration-tasks/'+otherId)).toBe(true));expect(screen.getByRole('button',{name:'Перевірити результат налаштування'}).disabled).toBe(true);
 await act(async()=>complete({data:check()}));await waitFor(()=>expect(screen.getByRole('button',{name:'Перевірити результат налаштування'}).disabled).toBe(false));expect(screen.queryByRole('checkbox')).toBeNull();expect(screen.queryByRole('button',{name:'Позначити задачу вирішеною'})).toBeNull();expect(client.post).not.toHaveBeenCalled();
});


it('creation task identifies a new unsaved product instead of implying that a SKU already exists',async()=>{
 mount();await screen.findByRole('link',{name:'Повернутися до створення товару'});
 expect(screen.getAllByText('Новий незбережений товар · Каблучки · Розмір · 29 мм').length).toBeGreaterThan(0);
 expect(client.post).not.toHaveBeenCalled();
});

